### ISSUE TITLE
[BUG REPORT]: Bugs observed using 0.0.3-alpha

### ISSUE THREAD

**Issue by Tekunalogy** [DeepwaterExploration/DWE_OS#315]
### DWE OS 0.0.3-alpha Bug Reports

Not applicable

### Describe the bug

- The templates for issues are not adapted for this repo (see above)
- No other cameras besides eHD 3.0 work
- python libs are not able to be install properly (`--break-system-packages` is needed for the current version)
- have to manually run `python3 run_release.py`
- gstreamer libs are not part of installation command
- Need to include instructions to download, unpack, install, and run the release (and maybe also save it to always run on boot)
    - `wget` for downloading
    - `tar -xf` for unpacking
- In the UI, Add the ability to see connected clients IP address and have an auto-fill of that IP address when adding stream endpoints.
- In the UI, keep the endpoints section expanded by default if there is an active stream
- In the UI, add default IP setting
- switching between streaming modes (such as h264 and mjpeg) is buggy and unstable.
- port numbers don't seem to increment

### To Reproduce

.

### Expected behavior

.

### Additional comments

```
sudo apt install libglib2.0-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libudev-dev libboost-all-dev gstreamer1.0-tools gstreamer1.0-x gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-libav
```

```
--break-system-packages
```

**Comment by brandonhs** [comment]
## Main Bugs

- [X] Fix template issues
- [x] Support for other cameras
- [X] Python virtual environment
- [X] Ease of release running

```sh
tar -xvzf release.tar.gz
cd release
sh install_requirements.sh
sh create_venv.sh
sh run_release.sh
```

- [x] Ease of installation
- [x] Installation and startup support
- [X] gstreamer commands in installation command
- [x] switching between streaming modes (such as h264 and mjpeg) is buggy and unstable.

## UI

- [ ] ability to see connected clients IP address and have an auto-fill of that IP address when adding stream endpoints
- [x] keep the endpoints section expanded by default if there is an active stream
- [x] add default IP setting
- [x] port increment

## Missing Features

- [x] Wifi

**Comment by Tekunalogy** [comment]
Also, python3 pip isn't installed on rpi by default, so that may or may not be needed in the future

**Comment by brandonhs** [comment]
Good to know, thanks

**Comment by Tekunalogy** [comment]
there is no `create_venv.sh` or `run_release.sh` file in the release.

**Comment by Tekunalogy** [comment]
dark theme needs to be default on first boot, hehe
